// ---- Hand-drawn item and tool icons -------------------------------------------
// Every tool you hold and every thing you carry, drawn pixel by pixel on a
// 16x16 grid in bright, even colours with a soft dark outline added round the
// edge afterwards. Icons.js prefers these over its procedural ones whenever a
// name is in here.
const IconArt = (() => {
  // one palette for the lot, so the whole bag of icons belongs together
  const PALETTE = {
    k: '#2e2430', K: '#1e1a22',                                  // ink
    w: '#c98a4a', W: '#eab06a', v: '#8a5530',                    // wood
    m: '#aeb8c8', M: '#eef3fa', n: '#6c7690',                    // steel
    g: '#5cb04a', G: '#a4e070', h: '#337a34',                    // leaf
    c: '#f28a2c', C: '#ffc070', d: '#b8561c',                    // orange
    r: '#e44a3c', R: '#ff9c86', q: '#a42a26',                    // red
    y: '#f8cc3c', Y: '#fff2a4', u: '#c88c1c',                    // yellow
    b: '#4ea4e6', B: '#b0e4ff', j: '#2a68aa',                    // blue
    e: '#8a5a3a', E: '#b8845a', f: '#5a3822',                    // brown
    t: '#ecd4a2', T: '#fff4d2', s: '#c4a270',                    // canvas
    x: '#ffffff', z: '#d4d8e2', Z: '#9ca2b0',                    // white
    p: '#f6a2bc', P: '#ffd4e0', i: '#a474d6', I: '#d8b8f6',      // pink, purple
    a: '#e8a878', A: '#ffd8b4', l: '#c07a52',                    // skin
  };
  const T = {
    t_drag: [
      '................',
      '.....aa.........',
      '...aaAAa.aa.....',
      '..aAAAAaaAAa....',
      '..aAAaAAaAAaaa..',
      '..aAAaAAaAAaAAa.',
      '..aAAaAAaAAaAAa.',
      'aaaAAAAAAAAAAAa.',
      'aAAaAAAAAAAAAAa.',
      'aAAAAAAAAAAAAla.',
      '.aAAAAAAAAAAAla.',
      '..aAAAAAAAAAla..',
      '...aAAAAAAAla...',
      '....llllllll....',
      '....bBBBBBBb....',
      '....jjjjjjjj....',
    ],
    t_sickle: [
      '................',
      '.....MMMMMM.....',
      '...MMmmmmmmMn...',
      '..Mmmnnnnnmmmn..',
      '..Mmn.....nmmn..',
      '.Mmn.......nmn..',
      '.mmn........nn..',
      '.mn.............',
      '..Ww............',
      '..vwW...........',
      '...vwW..........',
      '....vwW.........',
      '.....vwW........',
      '......vwW.......',
      '.......vv.......',
      '................',
    ],
    t_hoe: [
      '................',
      '...........MMMm.',
      '..........MmmmmM',
      '..........nWmmmn',
      '.........vW..mmn',
      '........vW....nn',
      '.......vW.......',
      '......vW........',
      '.....vW.........',
      '....vW..........',
      '...vW...........',
      '..vW............',
      '.vW.............',
      '.v..............',
      '................',
      '................',
    ],
    t_water: [
      '................',
      '.....jjjj.......',
      '....j....j......',
      '....j....j...BB.',
      '..bbbbbbbbb..BBj',
      '.bBBBbbbbbbj.bj.',
      '.bBbbbbbbbbjbj..',
      '.bBbbbbbbbbbj...',
      '.bBbbbbbbbbj....',
      '.bbbbbbbbbbj....',
      '.bbbbbbbbbbj....',
      '.jbbbbbbbbjj....',
      '..jjjjjjjjj.....',
      '................',
      '................',
      '................',
    ],
    t_seed: [
      '................',
      '......e..e......',
      '.......ee.......',
      '......tttt......',
      '.....sTTTTs.....',
      '....tTttttts....',
      '...tTttttttts...',
      '..tTtttgttttts..',
      '..tTttghgtttts..',
      '..tTtttgGttttt..',
      '..tttttgttttss..',
      '..ttttttttttss..',
      '...sttttttsss...',
      '....ssssssss....',
      '................',
      '................',
    ],
    t_moss: [
      '................',
      '................',
      '......G.........',
      '...G..Gg..G.....',
      '...Gg.gG.Gg..G..',
      '....gGgg.gG.Gg..',
      '.G..ggGg.gg.g...',
      '.Gg.hgggGgg.g.G.',
      '..g.hggggghgggg.',
      '..ghhgghgghggh..',
      '...hhhhhhhhhhh..',
      '..eEEeEEEeEEEe..',
      '..eeeeeeeeeeee..',
      '...ffffffffff...',
      '................',
      '................',
    ],
    t_destroy: [
      '................',
      '...yyyy.........',
      '..yYYYYy........',
      '.uyyyyyyu.......',
      '..rrrrrr........',
      '..rxKrrr.rr.....',
      '..rrrrrr.rrrrrr.',
      '...rrrr.rRRrrrqq',
      '....qqqqrRrrrrrq',
      '.....q..qrrrrrq.',
      '....q.q..qqqqq..',
      '...q..q..q..q...',
      '..q...q.q...q...',
      '................',
      '................',
      '................',
    ],
    t_food: [
      '................',
      '................',
      '................',
      '......c.........',
      '.....cCd..G.....',
      '....gGcd.GgG....',
      '...GgggcGgggh...',
      '..BBBBBBBBBBBB..',
      '.jbBBbbbbbbbbbj.',
      '.jbBbbbbbbbbbjj.',
      '..jbbbbbbbbbjj..',
      '...jjjjjjjjjj...',
      '................',
      '................',
      '................',
      '................',
    ],
    t_scoop: [
      '................',
      '..............W.',
      '.............vW.',
      '............vW..',
      '...........vW...',
      '..........vW....',
      '.........vW.....',
      '...EEE..vW......',
      '..EeeEf.W.......',
      '.MeeeefM........',
      '.mMMMMMMm.......',
      '..mmmmmmn.......',
      '...nnnnn........',
      '................',
      '................',
      '................',
    ],
    t_shovel: [
      '...........WWW..',
      '...........W.W..',
      '...........vWv..',
      '...........vW...',
      '..........vW....',
      '.........vW.....',
      '........vW......',
      '.......vW.......',
      '...MMMnW........',
      '..MmmmMn........',
      '..MmmmmMn.......',
      '..mmmmmmn.......',
      '..nmmmmmn.......',
      '...nmmmn........',
      '....nnn.........',
      '................',
    ],
    t_hammer: [
      '................',
      '..MMMMMMMMMM....',
      '.MmmmmmmmmmmMn..',
      '.nmmmmmmmmmmnn..',
      '..nnnnWwnnnn....',
      '......Wwv.......',
      '......Wwv.......',
      '......Wwv.......',
      '......Wwv.......',
      '......Wwv.......',
      '......Wwv.......',
      '......Wwv.......',
      '......vvv.......',
      '................',
      '................',
      '................',
    ],
    ph_key: [
      '.....zzzzzz.....',
      '....zxxxxxxz....',
      '....zxxKKxxz....',
      '....zxPPPIxz....',
      '....zxPpIIxz....',
      '....zxpIIbxz....',
      '....zxIIbbxz....',
      '....zxIbbbxz....',
      '....zxbbbjxz....',
      '....zxbbjjxz....',
      '....zxbjjjxz....',
      '....zxxxxxxz....',
      '....zxxZZxxz....',
      '.....zzzzzz.....',
      '................',
      '................',
    ],
    c_carrot: [
      '................',
      '..........G.G...',
      '.........GgGg...',
      '..........gGgG..',
      '.........Ccgg...',
      '........CCcd....',
      '.......CCccd....',
      '......Cccccd....',
      '.....Cccdcd.....',
      '....Cccccd......',
      '...cccdcd.......',
      '..cccccd........',
      '..ccdd..........',
      '..dd............',
      '................',
      '................',
    ],
    c_cabbage: [
      '................',
      '................',
      '.....hgggh......',
      '...hgGGGGGgh....',
      '..hgGGgGGGGgh...',
      '..gGGgGGgGGGg...',
      '.hgGGGgggGGGgh..',
      '.hgGGgGGGgGGgh..',
      '.hggGgGGGgGggh..',
      '..hggggGggggh...',
      '..hhggggggghh...',
      '...hhhhhhhhh....',
      '................',
      '................',
      '................',
      '................',
    ],
    c_potato: [
      '................',
      '................',
      '................',
      '.....ssss.......',
      '...sstttTss.....',
      '..stttTTttts....',
      '..sttettTTtse...',
      '.estttttteTtse..',
      '.essttttttttse..',
      '..essssesssse...',
      '...eeeeeeeee....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    c_pumpkin: [
      '................',
      '................',
      '.......hv.......',
      '......hv........',
      '...cCCcccCCc....',
      '..cCCccdcCCcd...',
      '.cCCcdccdcCccd..',
      '.cCccdccdccCcd..',
      '.cCccdccdcccdd..',
      '.cccdccccdccdd..',
      '..ccdccccdcdd...',
      '...dddddddddd...',
      '................',
      '................',
      '................',
      '................',
    ],
    c_apple: [
      '................',
      '.......v.G......',
      '.......vGGh.....',
      '....rrrvrrr.....',
      '...rRRrrrrrq....',
      '..rRRrrrrrrrq...',
      '..rRrrrrrrrrq...',
      '..rrrrrrrrrrq...',
      '..rrrrrrrrrqq...',
      '...rrrrrrrqq....',
      '....qq.qqq......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    c_lemon: [
      '................',
      '................',
      '.........hG.....',
      '........hgG.....',
      '.....uyyyyu.....',
      '...uyYYyyyyyu...',
      '..uyYYyyyyyyyu..',
      '.uyYyyyyyyyyyyu.',
      '..uyyyyyyyyyyu..',
      '...uyyyyyyyyu...',
      '.....uuuuuu.....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    c_sunroot: [
      '................',
      '.......G........',
      '......gGh.......',
      '.......h........',
      '.....yyyy.......',
      '...yyYYyyyu.....',
      '..yYYyyyyyyu.u..',
      '..yYyyyuyyyyuyu.',
      '.uyyyyyyyyyyyyu.',
      '.uyyuyyyyyuyyu..',
      '..uuyyyyyyyuu...',
      '....uuuuuuu.....',
      '................',
      '................',
      '................',
      '................',
    ],
    c_goldwheat: [
      '................',
      '.......Y........',
      '......YyY.......',
      '.....YyuyY......',
      '......yuy.......',
      '.....YyuyY......',
      '......yuy.......',
      '.....YyuyY......',
      '......yuy.......',
      '.......u........',
      '.......g........',
      '......Gg........',
      '.......g.G......',
      '.......gg.......',
      '.......g........',
      '................',
    ],
    c_ashgrass: [
      '................',
      '................',
      '....GG...GG.....',
      '...GggG.GggG....',
      '...GgggGgggG....',
      '....ggghggg.....',
      '.GG..gghgg..GG..',
      'GggG..ghg..GggG.',
      'GgggGhhhhhGgggG.',
      '.gggggghggggggh.',
      '..hhgggh.gggghh.',
      '.......h........',
      '.......h........',
      '......hh........',
      '................',
      '................',
    ],
    c_gumnut: [
      '................',
      '..........hg....',
      '........hggG....',
      '......hggGG.....',
      '.....hgGGg......',
      '....hgGg........',
      '...hgg..........',
      '...h..ee........',
      '..h..eEEe.ee....',
      '.....eEee.eEe...',
      '......ee..eee...',
      '..........ff....',
      '................',
      '................',
      '................',
      '................',
    ],
    o_plain: [
      '................',
      '................',
      '................',
      '....EEEEEEEEE...',
      '...EETEEEEEEEe..',
      '..EEEEEEEEEEeef.',
      '..eeeeeeeeeeeff.',
      '..eeEeeeeeeeeff.',
      '..eeeeeeeeeeeff.',
      '..eeeeeeeefeeff.',
      '..eeeeeeeeeeeff.',
      '..eeeeeeeeeeef..',
      '..ffffffffffff..',
      '................',
      '................',
      '................',
    ],
    o_rich: [
      '................',
      '..Y.............',
      '.YxY............',
      '..Y.eeeeeeeee...',
      '...eeEeeeeeeef..',
      '..eeeeeeeeeeffK.',
      '..ffffffffffffK.',
      '..ffeffffffffKK.',
      '..ffffffffffffK.',
      '..ffffffffKfffK.',
      '..ffffffffffffK.',
      '..fffffffffffK..',
      '..KKKKKKKKKKKK..',
      '...........Y....',
      '..........YxY...',
      '...........Y....',
    ],
    wdollar: [
      '................',
      '.....uuuuuu.....',
      '...uuyyyyyyuu...',
      '..uyYYyyyyyyyu..',
      '..uYYyyyyyyyyu..',
      '.uyYyuyyyyuyyyu.',
      '.uyyyuyyyyuyyyu.',
      '.uyyyuyuuyuyyyu.',
      '.uyyyuuyyuuyyyu.',
      '.uyyyuyyyyuyyyu.',
      '..uyyyyyyyyyyu..',
      '..uuyyyyyyyyuu..',
      '...uuyyyyyyuu...',
      '.....uuuuuu.....',
      '................',
      '................',
    ],
    lock: [
      '................',
      '................',
      '.....nnnnn......',
      '....n.....n.....',
      '....n.....n.....',
      '....n.....n.....',
      '...yyyyyyyyy....',
      '...yYYYYYYYu....',
      '...yYyyuyyyu....',
      '...yYyyKyyyu....',
      '...yYyyKyyyu....',
      '...yyyyyyyyu....',
      '...uuuuuuuuu....',
      '................',
      '................',
      '................',
    ],
  };
  const OUT = '#3a2c34';
  function build(name) {
    const rows = T[name];
    if (!rows) return null;
    const H = rows.length, W = rows[0].length;
    const { c, g } = Art.cv(W + 2, H + 2);
    const on = (x, y) => y >= 0 && y < H && x >= 0 && x < W && rows[y][x] !== '.';
    // the soft outline first, one pixel round everything that is not empty
    g.fillStyle = OUT;
    for (let y = -1; y <= H; y++) for (let x = -1; x <= W; x++) {
      if (on(x, y)) continue;
      if (on(x - 1, y) || on(x + 1, y) || on(x, y - 1) || on(x, y + 1)) g.fillRect(x + 1, y + 1, 1, 1);
    }
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      g.fillStyle = PALETTE[ch] || '#ff00ff';
      g.fillRect(x + 1, y + 1, 1, 1);
    }
    return c;
  }
  return { build, has: (n) => !!T[n], names: () => Object.keys(T), T };
})();
